### ISSUE TITLE
No module named 'Evaluation'

### ISSUE THREAD

**Issue by gopal-gcek** [dvysardana/RecommenderSystems_PyData_2016#1]
i have installed anaconda3 and python3. but when i execute the import Evaluation as Evaluation
in python3 it will display following error
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-55-4f843c561a3c> in <module>
----> 1 import Evaluation as eva

ModuleNotFoundError: No module named 'Evaluation'

**Comment by fheilz** [comment]
try: pip3 install Evaluation

**Comment by gopal-gcek** [comment]
when run pip3 install Evaluation
Could not find a version that satisfies the requirement Evaluation (from versions: )
No matching distribution found for Evaluation

**Comment by gopal-gcek** [comment]
thank you for ur suggestion

**Comment by NeelKanwal** [comment]
It does not work. 

 pip3 install Evaluation
               ^
SyntaxError: invalid syntax

**Comment by khangkontum** [comment]
have you fixed it yet?

**Comment by irohits** [comment]
Use this :-

!pip3 install Evaluation
